[build]
  environment = { PYTHON_VERSION = "3.10" }
  command = "npm run build"
  publish = "dist"
  
[functions]
  # This tells Netlify where to look for your functions
  directory = "netlify/functions"